# Generated by Django 3.1.6 on 2021-02-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210203_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='languages',
            new_name='language',
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('gbp', 'GBP'), ('eur', 'EUR'), ('ghs', 'GHS'), ('ngn', 'NGN'), ('xpf', 'XPF'), ('zar', 'ZAR')], max_length=3, null=True),
        ),
    ]
